#!/bin/bash

if [ $1 != "" ] ; then
    if [ $1 == "armv6" -o $1 == "i386" ] ; then
        ARCH=$1
    fi
fi

if [ -z $ARCH ] ; then
    echo "Usage: $0 [armv6 | i386]"
    exit 1
fi

LIB_PATH=$PWD/$1
if [ ! -s "$LIB_PATH" ] ; then
    mkdir "$LIB_PATH"
fi
rm "$LIB_PATH"/*.a

OPTIONS="--disable-doc --disable-ffmpeg --disable-ffplay --disable-ffserver --disable-ffprobe --disable-muxers --disable-encoders --disable-decoders --disable-demuxers --enable-decoder=h264 --enable-demuxer=h264 --disable-parsers --enable-parser=h264 --disable-filters --disable-bsfs --disable-protocols --disable-network --disable-zlib --disable-bzlib --disable-devices --disable-hwaccels --disable-indevs --disable-outdevs --enable-pic --disable-debug"

cd ffmpeg
make clean

if [ $ARCH == "armv6" ] ; then
    ./configure --enable-cross-compile --arch=arm --target-os=darwin --cc=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc --as='../gas-preprocessor/gas-preprocessor.pl /Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/gcc' --sysroot=/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS4.2.sdk --cpu=arm1176jzf-s --extra-cflags='-arch armv6' --extra-ldflags='-arch armv6' $OPTIONS
else
    ./configure --enable-cross-compile --arch=i386 --target-os=darwin --cc=/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/gcc --sysroot=/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator4.2.sdk --extra-cflags='-isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator4.2.sdk' --extra-cflags='-arch i386' --extra-ldflags='-arch i386' --disable-mmx $OPTIONS
fi

make

mv libavcodec/libavcodec.a "$LIB_PATH"
mv libavdevice/libavdevice.a "$LIB_PATH"
mv libavformat/libavformat.a "$LIB_PATH"
mv libavutil/libavutil.a "$LIB_PATH"
mv libswscale/libswscale.a "$LIB_PATH"